### ISSUE TITLE
Display#loadFont not working on Linux

### ISSUE THREAD

**Issue by Phillipus** [archi-contribs/fontloader-plugin#1]
Disolay#loadFont() returns true on Linux but the font does not seem to be registered.

To load a font and then list all loaded fonts:

```
boolean success = Display.getDefault().loadFont(fontPath);

for(FontData fd : Display.getDefault().getFontList(null, true)) {
    System.out.println(fd.getName());
}
```

Edit - listing fonts with the the loaded font being in the list only works on Windows. On Mac, the font is loaded and is available in a font dialog but for some reason is not returned by `Display.getDefault().getFontList()`

I searched to see if this is a known issue but couldn't find anything.

We could try a different font or see if Linux requires a certain font format.

**Comment by jbsarrodie** [comment]
Thank you for your investigation, but I think I will simply consider this plugin not compatible with Linux. And btw, the original use-case (users not able to install a font because of local right issues) doesn't exist on Linux.

Here I'm targetting "Enterprise" users, who usually don't run Linux.

>I searched to see if this is a known issue but couldn't find anything.

I found people having the exact same issue some years ago, but didn't find any workaround.

**Comment by Phillipus** [comment]
Close this as it now works on Linux in main Archi code.
